language: python
services:
  - redis-server
python:
  - "3.5"
  - "3.4"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO="django>=1.5"
install:
  - pip install $DJANGO --use-mirrors
  - pip install -q redis --use-mirrors
script: python setup.py nosetests
