language: python
services:
  - redis-server
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5"
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.2"
      env: DJANGO="django>=1.4,<1.5"
     # Django 1.9+ no longer supports python 3.2/3.3
    - python: "3.2"
      env: DJANGO="Django<1.9"
    - python: "3.3"
      env: DJANGO="Django<1.9"
    - python: "2.6"
      env: DJANGO="django>=1.5"
install:
  - pip install $DJANGO --use-mirrors
  - pip install -q redis --use-mirrors
script: python setup.py nosetests
